---
sudo: required
dist: trusty
language: ruby
install:
  - source "$PWD/versions"
  - rvm use "$RUBY_VERSION" --install --binary
  - nvm install "$NODE_VERSION"
  - npm install -g npm
script:
  - make install
  - make build
after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && make deploy
