sudo: required
dist: trusty
language: ruby
install:
  - source "$PWD/versions"
  - rvm use "$RUBY_VERSION" --install --binary
  - nvm install "$NODE_VERSION"
  - npm install -g npm
  - npm install -g gitbook-cli
  - npm install -g npm-registry-client
script:
  - make 
after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && make install
env:
  global:
  - secure: CohvEYFET5ZDkvAeV0XCOWtKcjXgRU8FeVwZx1uMu4T99pdrtt2xs9BfkUOouSdQACUAuVy0U/PDJjJ/L3PZowio40vI5E1tfsXyZIL3nOADcdEBKZEEAbR9liA4G7NJ8AEsh/CkM0Kkbx+jfw6hPm7d+xJqPIYfA700F5NWb5dZNpQagsHwhP0ok1sGv/2sYGSdWCoQg+UF50/941lvi6ogrdz6v1Pxa7+ZBwgRls86SnYCB5BC+zdSEv897rJvLPLG6IMABXV+XZvFo4M0JfQFiCfOZU+dnyd2Nxt7+ESQIk7GYKrkk5LYmebATbeE9/EVlptbEmsbilNh45yARbxhawGR1/PTQqx6SVJ/N6tVi9DQU58N1x4hA8kdAutcmToprRwcX9t434veVCd5LLH0M8q4di2dQLYrrujUuCufGzDYsPsVgEq3bI8nn9qJIM8PiQm6IFyyj2VhG50PE6yQJzf21YBIhFFNnpSaSV0qRooxuz/YGJI4jbE54bpeQ/Bii6M/JTbmhtbzuaogbpo54x1edloZvRh+qEGt2jSqOfliZK7IR9bwx4RpAFB4qx/+Wl11jUo21j995vu34AVohWjCRB8MnZI+ossPNpx7XrHSu1HcjeAOYglPeMDtfMxGc2KX1QU8owbwWWeraDt7XyPeDfx4FXSv/qpSk9g=
